<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add category'); ?>"
           href="<?php echo $this->url('', array('controller' => 'category', 'action' => 'update')); ?>"><i
                class="fa fa-folder-open"></i> <?php _e('Add category'); ?></a>
    </p>
    <h3><?php _e('List of all categories'); ?></h3>
    <table class="table table-striped table-bordered table-sm">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $category) { ?>
            <?php
            if ($category['status'] == 1) {
                $labelIdClass = 'label-success';
            } else {
                $labelIdClass = 'label-warning';
            }
            ?>
            <tr>
                <td><span
                        class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($category['id']); ?></span>
                </td>
                <td><?php echo $this->escape($category['title']); ?></td>
                <td>
                    <?php if ($config['category_active']) { ?>
                    <a target="_blank" class="btn btn-success btn-sm" title="<?php _e('View'); ?>"
                       href="<?php echo $this->url('plans', array('category' => $category['id'])); ?>"><i
                            class="fa fa-eye"></i> <?php _e('View'); ?></a>
                    <?php } ?>
                    <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', array('action' => 'update', 'id' => $category['id'])); ?>"><i
                            class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>