<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of all categories'); ?></h3>
    <?php if (isset($list) && !empty($list)) { ?>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $category) { ?>
                <?php if ($category['status'] == 1) {
                    $labelIdClass = 'label-success';
                } else {
                    $labelIdClass = 'label-warning';
                } ?>
                <tr>
                    <td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($category['id']); ?></span></td>
                    <td><?php echo $this->escape($category['title']); ?></td>
                    <td>
                        <?php if ($config['category_active']) { ?>
                            <a target="_blank" class="btn btn-success btn-sm" title="<?php _e('View'); ?>"
                               href="<?php echo $this->url('plans', ['category' => $category['id']]); ?>"><i
                                        class="fa fa-eye"></i> <?php _e('View'); ?></a>
                        <?php } ?>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $category['id']]); ?>">
                            <i class="fa fa-edit"></i> <?php _e('Edit'); ?>
                        </a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger">
            <?php _e('No category added yet, please add new one'); ?>
        </div>
    <?php } ?>
</div>