<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="page-header">
        <h1><?php echo $config['index_text_title']; ?></h1>
    </div>
    <?php if (!empty($config['index_text_description'])) { ?>
        <div class="clearfix">
            <?php echo $config['index_text_description']; ?>
        </div>
    <?php } ?>
    <?php if ($config['view_type'] == 'list') { ?>
        <?php foreach ($categories as $category) { ?>
            <?php if (!empty($category['plans'])) { ?>
                <?php if (count($category['plans']) == 1) {
                    $class = 'col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4';
                } elseif (count($category['plans']) == 2) {
                    $class = 'col-xs-12 col-sm-6 col-md-3 col-md-offset-2';
                } elseif (count($category['plans']) == 3) {
                    $class = 'col-xs-12 col-sm-4 col-md-4';
                } elseif (count($category['plans']) == 4) {
                    $class = 'col-xs-12 col-sm-6 col-md-3';
                } elseif (count($category['plans']) == 5) {
                    $class = 'col-xs-12 col-sm-4 col-md-2';
                } elseif (count($category['plans']) == 6) {
                    $class = 'col-xs-12 col-sm-3 col-md-2';
                } else {
                    $class = 'col-xs-12 col-sm-6 col-md-3';
                } ?>
                <div class="clearfix plans-category-list">
                    <?php if (!empty($category['title'])) { ?>
                        <div class="plans-category-list-title text-center">
                            <h2><?php echo $this->escape($category['title']); ?></h2>
                        </div>
                    <?php } ?>
                    <?php foreach($category['plans'] as $plan) { ?>
                        <div class="<?php echo $class; ?>">
                            <div class="<?php echo $this->escape($plan['color']); ?>">
                            <ul class="pricing">
                                <li>
                                    <i class="fa <?php echo $this->escape($plan['icon']); ?>"></i>
                                    <big><?php echo $this->escape($plan['title']); ?></big>
                                </li>
                                <?php if (!empty($plan['description_1'])) { ?>
                                    <li><?php echo $this->escape($plan['description_1']); ?></li>
                                <?php } ?>
                                <?php if (!empty($plan['description_2'])) { ?>
                                    <li><?php echo $this->escape($plan['description_2']); ?></li>
                                <?php } ?>
                                <?php if (!empty($plan['description_3'])) { ?>
                                    <li><?php echo $this->escape($plan['description_3']); ?></li>
                                <?php } ?>
                                <?php if (!empty($plan['description_4'])) { ?>
                                    <li><?php echo $this->escape($plan['description_4']); ?></li>
                                <?php } ?>
                                <?php if (!empty($plan['description_5'])) { ?>
                                    <li><?php echo $this->escape($plan['description_5']); ?></li>
                                <?php } ?>
                                <?php if (!empty($plan['description_6'])) { ?>
                                    <li><?php echo $this->escape($plan['description_6']); ?></li>
                                <?php } ?>
                                <?php if (!empty($plan['description_7'])) { ?>
                                    <li><?php echo $this->escape($plan['description_7']); ?></li>
                                <?php } ?>
                                <?php if (!empty($plan['description_8'])) { ?>
                                    <li><?php echo $this->escape($plan['description_8']); ?></li>
                                <?php } ?>
                                <?php if (!empty($plan['description_9'])) { ?>
                                    <li><?php echo $this->escape($plan['description_9']); ?></li>
                                <?php } ?>
                                <?php if (!empty($plan['description_10'])) { ?>
                                    <li><?php echo $this->escape($plan['description_10']); ?></li>
                                <?php } ?>
                                <li>
                                    <h3><?php echo $this->escape($plan['price_view']); ?></h3>
                                    <span><?php echo $this->escape($plan['time_period_view']); ?></span>
                                </li>
                                <li>
                                    <a href="<?php echo $this->escape($plan['orderUrl']); ?>" class="order-button" id="product1-order-button">
                                        <?php _e('Order'); ?>
                                    </a>
                                </li>
                            </ul>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
        <?php } ?>
    <?php } elseif ($config['view_type'] == 'tab') { ?>
        <div class="clearfix plans-category-tab">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <?php foreach ($categories as $category) { ?>
                    <?php if (!empty($category['plans'])) { ?>
                        <li role="presentation"<?php if ($category['id'] == 0) { echo ' class="active"';} ?>>
                            <a href="#category-<?php echo $this->escape($category['id']); ?>" aria-controls="category-<?php echo $this->escape($category['id']); ?>" role="tab" data-toggle="tab">
                                <?php if ($category['id'] == 0) {
                                    _e('Main plans');
                                } else {
                                    echo $this->escape($category['title']);
                                } ?>
                            </a>
                        </li>
                    <?php } ?>
                <?php } ?>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <?php foreach ($categories as $category) { ?>
                    <?php if (!empty($category['plans'])) { ?>
                        <?php if (count($category['plans']) == 1) {
                            $class = 'col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4';
                        } elseif (count($category['plans']) == 2) {
                            $class = 'col-xs-12 col-sm-6 col-md-3 col-md-offset-2';
                        } elseif (count($category['plans']) == 3) {
                            $class = 'col-xs-12 col-sm-4 col-md-4';
                        } elseif (count($category['plans']) == 4) {
                            $class = 'col-xs-12 col-sm-6 col-md-3';
                        } elseif (count($category['plans']) == 5) {
                            $class = 'col-xs-12 col-sm-4 col-md-2';
                        } elseif (count($category['plans']) == 6) {
                            $class = 'col-xs-12 col-sm-3 col-md-2';
                        } else {
                            $class = 'col-xs-12 col-sm-6 col-md-3';
                        } ?>
                        <div role="tabpanel" class="tab-pane<?php if ($category['id'] == 0) { echo ' active';} ?> clearfix" id="category-<?php echo $this->escape($category['id']); ?>">
                            <?php foreach($category['plans'] as $plan) { ?>
                                <div class="<?php echo $class; ?>">
                                    <div class="<?php echo $this->escape($plan['color']); ?>">
                                    <ul class="pricing">
                                        <li>
                                            <i class="fa <?php echo $this->escape($plan['icon']); ?>"></i>
                                            <big><?php echo $this->escape($plan['title']); ?></big>
                                        </li>
                                        <?php if (!empty($plan['description_1'])) { ?>
                                            <li><?php echo $this->escape($plan['description_1']); ?></li>
                                        <?php } ?>
                                        <?php if (!empty($plan['description_2'])) { ?>
                                            <li><?php echo $this->escape($plan['description_2']); ?></li>
                                        <?php } ?>
                                        <?php if (!empty($plan['description_3'])) { ?>
                                            <li><?php echo $this->escape($plan['description_3']); ?></li>
                                        <?php } ?>
                                        <?php if (!empty($plan['description_4'])) { ?>
                                            <li><?php echo $this->escape($plan['description_4']); ?></li>
                                        <?php } ?>
                                        <?php if (!empty($plan['description_5'])) { ?>
                                            <li><?php echo $this->escape($plan['description_5']); ?></li>
                                        <?php } ?>
                                        <?php if (!empty($plan['description_6'])) { ?>
                                            <li><?php echo $this->escape($plan['description_6']); ?></li>
                                        <?php } ?>
                                        <?php if (!empty($plan['description_7'])) { ?>
                                            <li><?php echo $this->escape($plan['description_7']); ?></li>
                                        <?php } ?>
                                        <?php if (!empty($plan['description_8'])) { ?>
                                            <li><?php echo $this->escape($plan['description_8']); ?></li>
                                        <?php } ?>
                                        <?php if (!empty($plan['description_9'])) { ?>
                                            <li><?php echo $this->escape($plan['description_9']); ?></li>
                                        <?php } ?>
                                        <?php if (!empty($plan['description_10'])) { ?>
                                            <li><?php echo $this->escape($plan['description_10']); ?></li>
                                        <?php } ?>
                                        <li>
                                            <h3><?php echo $this->escape($plan['price_view']); ?></h3>
                                            <span><?php echo $this->escape($plan['time_period_view']); ?></span>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->escape($plan['orderUrl']); ?>" class="order-button" id="product1-order-button">
                                                <?php _e('Order'); ?>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                </div>
                            <?php } ?>
                        </div>
                    <?php } ?>
                <?php } ?>
            </div>
        </div>
    <?php } ?>
</div>