<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="alert alert-success">
        <h1><?php _e('Finish order payment'); ?></h1>
        <?php if (isset($invoices) && !empty($invoices)) { ?>
            <?php foreach ($invoices as $invoice) { ?>
                <p><?php echo $invoice['log']['message']; ?> <?php echo $invoice['log']['gatewayMessage']; ?></p>
            <?php } ?>
        <?php } ?>
        <p><?php echo sprintf(__('You pay your order at <strong>%s</strong> by <strong>%s</strong> gateway And your order id is <strong>%s</strong>'), $orderOrder['time_payment_view'], $orderOrder['gateway'], $orderOrder['code']); ?></p>
    </div>
    <p>
        <a class="btn btn-primary" title="<?php _e('Order link'); ?>"
           href="<?php echo $orderOrder['order_link']; ?>"><?php _e('Order link'); ?></a>
        <a class="btn btn-primary" title="<?php _e('User panel'); ?>"
           href="<?php echo $orderOrder['user_link']; ?>"><?php _e('User panel'); ?></a>
        <a class="btn btn-primary" title="<?php _e('Shop index'); ?>"
           href="<?php echo $orderOrder['index_link']; ?>"><?php _e('Plan list'); ?></a>
    </p>
</div>
<pre><?php print_r($orderOrder); ?></pre>
<pre><?php print_r($invoice); ?></pre>
<pre><?php print_r($orderPlan); ?></pre>
<pre><?php print_r($plan); ?></pre>