<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="alert alert-success">
        <h1><?php _e('Finish order payment'); ?></h1>
        <?php if (isset($invoices) && !empty($invoices)) { ?>
            <?php foreach ($invoices as $invoice) { ?>
                <p><?php echo $invoice['log']['message']; ?> <?php echo $invoice['log']['gatewayMessage']; ?></p>
            <?php } ?>
        <?php } ?>
        <p><?php echo sprintf(__('You pay your order at <strong>%s</strong> by <strong>%s</strong> gateway And your order id is <strong>%s</strong>'), $orderOrder['time_payment_view'], $orderOrder['gateway'], $orderOrder['code']); ?></p>
    </div>

    <div class="clearfix">
        <div class="col-md-12 text-center">
            <h3><?php _e('Your select plan'); ?></h3>
            <p><?php echo $message; ?></p>
        </div>
        <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
            <ul class="pricing <?php echo $this->escape($plan['color']); ?>">
                <li>
                    <i class="fa <?php echo $this->escape($plan['icon']); ?>"></i>
                    <big><?php echo $this->escape($plan['title']); ?></big>
                </li>
                <?php if (!empty($plan['description_1'])) { ?>
                    <li><?php echo $this->escape($plan['description_1']); ?></li>
                <?php } ?>
                <?php if (!empty($plan['description_2'])) { ?>
                    <li><?php echo $this->escape($plan['description_2']); ?></li>
                <?php } ?>
                <?php if (!empty($plan['description_3'])) { ?>
                    <li><?php echo $this->escape($plan['description_3']); ?></li>
                <?php } ?>
                <?php if (!empty($plan['description_4'])) { ?>
                    <li><?php echo $this->escape($plan['description_4']); ?></li>
                <?php } ?>
                <?php if (!empty($plan['description_5'])) { ?>
                    <li><?php echo $this->escape($plan['description_5']); ?></li>
                <?php } ?>
                <?php if (!empty($plan['description_6'])) { ?>
                    <li><?php echo $this->escape($plan['description_6']); ?></li>
                <?php } ?>
                <?php if (!empty($plan['description_7'])) { ?>
                    <li><?php echo $this->escape($plan['description_7']); ?></li>
                <?php } ?>
                <?php if (!empty($plan['description_8'])) { ?>
                    <li><?php echo $this->escape($plan['description_8']); ?></li>
                <?php } ?>
                <?php if (!empty($plan['description_9'])) { ?>
                    <li><?php echo $this->escape($plan['description_9']); ?></li>
                <?php } ?>
                <?php if (!empty($plan['description_10'])) { ?>
                    <li><?php echo $this->escape($plan['description_10']); ?></li>
                <?php } ?>
                <li>
                    <h3><?php echo $this->escape($plan['price_view']); ?></h3>
                    <span><?php echo $this->escape($plan['time_period_view']); ?></span>
                </li>
            </ul>
        </div>
    </div>
    <div class="text-center">
        <a class="btn btn-primary" title="<?php _e('Order link'); ?>"
           href="<?php echo $orderOrder['order_link']; ?>"><?php _e('Order link'); ?></a>
        <a class="btn btn-primary" title="<?php _e('User panel'); ?>"
           href="<?php echo $orderOrder['user_link']; ?>"><?php _e('User panel'); ?></a>
        <a class="btn btn-primary" title="<?php _e('Shop index'); ?>"
           href="<?php echo $orderOrder['index_link']; ?>"><?php _e('Plan list'); ?></a>
    </div>
</div>