<div class="<?php echo $class; ?>">
    <div class="<?php echo $this->escape($plan['color']); ?>">
        <ul class="pricing">
            <li>
                <i class="fa <?php echo $this->escape($plan['icon']); ?>"></i>
                <big><?php echo $this->escape($plan['title']); ?></big>
            </li>
            <?php if (!empty($plan['description_1'])) { ?>
                <li><?php echo $this->escape($plan['description_1']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_2'])) { ?>
                <li><?php echo $this->escape($plan['description_2']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_3'])) { ?>
                <li><?php echo $this->escape($plan['description_3']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_4'])) { ?>
                <li><?php echo $this->escape($plan['description_4']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_5'])) { ?>
                <li><?php echo $this->escape($plan['description_5']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_6'])) { ?>
                <li><?php echo $this->escape($plan['description_6']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_7'])) { ?>
                <li><?php echo $this->escape($plan['description_7']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_8'])) { ?>
                <li><?php echo $this->escape($plan['description_8']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_9'])) { ?>
                <li><?php echo $this->escape($plan['description_9']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_10'])) { ?>
                <li><?php echo $this->escape($plan['description_10']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_11'])) { ?>
                <li><?php echo $this->escape($plan['description_11']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_12'])) { ?>
                <li><?php echo $this->escape($plan['description_12']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_13'])) { ?>
                <li><?php echo $this->escape($plan['description_13']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_14'])) { ?>
                <li><?php echo $this->escape($plan['description_14']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['description_15'])) { ?>
                <li><?php echo $this->escape($plan['description_15']); ?></li>
            <?php } ?>
            <?php if (!empty($plan['link_title']) && !empty($plan['link_url'])) { ?>
                <li>
                    <a target="_blank" title="<?php echo $this->escape($plan['link_title']); ?>" href="<?php echo $this->escape($plan['link_url']); ?>">
                        <i class="fa fa-share-square-o"></i>
                        <?php echo $this->escape($plan['link_title']); ?>
                    </a>
                </li>
            <?php } ?>
            <?php if (!empty($plan['price_view']) || !empty($plan['time_period_view'])) { ?>
                <li>
                    <?php if (!empty($plan['price_view'])) { ?>
                        <h3><?php echo $this->escape($plan['price_view']); ?></h3>
                    <?php } ?>
                    <?php if (!empty($plan['time_period_view'])) { ?>
                        <span><?php echo $this->escape($plan['time_period_view']); ?></span>
                    <?php } ?>
                </li>
            <?php } ?>
            <?php if ($plan['price'] > 0) { ?>
                <li>
                    <a href="<?php echo $this->escape($plan['orderUrl']); ?>" class="order-button" id="product1-order-button">
                        <?php echo $this->escape($plan['order_title']); ?>
                    </a>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>